### ISSUE TITLE
Missing argument "INPUT_FILEPATH" in "make data"

### ISSUE THREAD

**Issue by chingyi071** [njtwomey/har_datasets#1]
Hi, I get the following message when I execute "make"
-------------------------------
Usage: make_dataset.py [OPTIONS] INPUT_FILEPATH OUTPUT_FILEPATH
Try "make_dataset.py --help" for help.

Error: Missing argument "INPUT_FILEPATH".

**Comment by njtwomey** [comment]
hi chingyi071
this repo currently has no functionality and is under development. i hope to upload the first functional system in the next two weeks so if you watch the repo you will get notified when this command will work.
cheers, 
niall
